export const SettingsTab = {
    PERSONAL: "PERSONAL",
    NOTIFICATION_AND_ALERTS: "NOTIFICATION_AND_ALERTS",
    PASSWORD_AND_SECURITY: "PASSWORD_AND_SECURITY",
    CONFIGURATIONS: "CONFIGURATIONS"
};


